### ISSUE TITLE
Database refactoring

### ISSUE THREAD

**Issue by kaidatavis** [Vis4Sense/HistoryMap#107]
Hi Reday, I found that the code for the historyMap database part does not follow the object-oriented structure defined in historyMap.js (historyMap.nodes is an example). I made an example in the new branch 'rebuild-mvc-db-refactoring': 965a93b8df9a47e218612159553ae9071f95769f. Please follow the pattern to refactor the code.

**Comment by kaimdx** [comment]
There are a few changes I have made: 

First, the 'database' is now not part of the historyMap.model and became an independent part. The historyMap looks like this now. I kept the old ```DBSave``` and ```DBLoad```. These should not be objects, but functions inside ```sessions```.
 
```
const historyMap = {
        model: {
            nodes: {},
            tree: {}, // real data
            tabs: {} // the status of the opened tabs in the browser
        },
        view: {
            vis: {},
            layout: {},
            redraw: {}
        },
        controller: {
            browser: {}
        },
        database: { // saving and loading the historyMap sessions
            user: {},
            sessions: {},
            // DBSave: {},
            // DBLoad: {}
        }
    };
```

**Comment by kaimdx** [comment]
Also, I created a new file ```database.js```, which will have all the code related to database, including user login. So far, I only moved part of the code in the ```historyMapData.js``` to there. Some of the code currently in the ```session.js``` should be in there, too.

**Comment by RedayY** [comment]
Wouldn't that be just to rename the functions ?

**Comment by kaimdx** [comment]
In ```database.js```, so far I created a ```user``` object (```= historyMap.database.user```). Inside ```user```, the ```profile``` object stores all the information related to the user and the ```addUser``` function is adapted from the old ```hisotryMap.API.DBSave.DBaddUser```.

Please follow this pattern and :
1. add any other 'user'-related object and functions to the ```user```;
2. create a ```session``` object and add 'session'-related object and functions there.

We can have a discussion if anything is not clear.

**Comment by RedayY** [comment]
@kaimdx just a quick question, what exactly supposed to be in database.js ?

currently session.js includes code that interacts purely with sessions, this means loading session and further. 

I would imagine that database.js has code related to saving to the DB ?

**Comment by RedayY** [comment]
DB Refactoring 1.0

See changes in https://github.com/Vis4Sense/SenseMapExtension/commit/274baf7efed852537f54fb194440bab54237fecf

- removed unused variables
- changed code to match OO Structure
- relocated code working with database to database.js
- refactored functions to meet new structure
- removed unused code and comments

to do:
slightly change Node2DB and Tree2DB
