### ISSUE TITLE
Display session title

### ISSUE THREAD

**Issue by kaidatavis** [Vis4Sense/HistoryMap#109]
Once a new sessions is created or a session is loaded, the HistoryMap window title (or some other display), should be updated to reflect this.

**Comment by HumzahJavid** [comment]
In src\historyMap\menu.js the section relating to creating a new session (line 106 to 114), the session title and other settings are not successfully appended to the DOM element with the "settings" id. 

Lines 112 and 113 are shown below.
```
            input.id = 'sessionName';
            document.getElementById('settings').appendChild(input);
```

No additional HTML is appended to the settings div, as seen in the Chrome inspector.
