### ISSUE TITLE
Delete branches in the github repository that are no longer needed

### ISSUE THREAD

**Issue by kaimdx** [Vis4Sense/HistoryMap#112]
We need to clean up the branches. There are too many currently. Please delete the branches if there are no longer needed. 

How to do this:
https://www.git-tower.com/learn/git/faq/delete-remote-branch
https://stackoverflow.com/questions/2003505/how-do-i-delete-a-git-branch-both-locally-and-remotely

**Comment by RedayY** [comment]
Deleted my two old branches as the code is included in rebuild-mvc

**Comment by kaimdx** [comment]
All the merged branches seem deleted.
