### ISSUE TITLE
Unable to add annotations in certain web pages

### ISSUE THREAD

**Issue by Naomi98** [Vis4Sense/HistoryMap#117]
On certain web pages, users are not able to click 'Save' button in order to add annotation on the highlighted text. The dialogue box for adding annotation becomes inactive.

For example:
Highlighting the text is possible.

![screenshot 25](https://user-images.githubusercontent.com/25341431/41771678-8f57103e-7633-11e8-9166-bd268ae63d75.png)

After typing the text in annotation box, it is not enabling the users to save them.

![screenshot 24](https://user-images.githubusercontent.com/25341431/41771546-231ffa34-7633-11e8-9ec8-e57a94074e4a.png)

Website: **https://www.jaguar.co.uk/jaguar-range/xe/xe-models/index.html**

**Comment by kaimdx** [comment]
Need to check this in the new 'HistoryMap'.
