### ISSUE TITLE
Nodes cross each other

### ISSUE THREAD

**Issue by Naomi98** [Vis4Sense/HistoryMap#121]
In the History map, if a node is opened again by clicking directly on it on the History Map, then the nodes get crossed with each other making an unclear display.

For example, in this image if we click on the node "Amazon Prime Day...", then that node is displaced below and the next nodes are mixed up.

![screenshot 59 _li](https://user-images.githubusercontent.com/25341431/42451306-be9ddd66-837e-11e8-963a-d1f0bd9d33c9.jpg)

We can see the same in this image.

![screenshot 60 _li](https://user-images.githubusercontent.com/25341431/42451353-e080885c-837e-11e8-98e7-31808d3be5d9.jpg)

**Comment by kaimdx** [comment]
It is the same bug as in #101
