### ISSUE TITLE
Pause not working

### ISSUE THREAD

**Issue by Naomi98** [Vis4Sense/HistoryMap#122]
The 'Pause' button is not working, that is, whenever it  is pressed, the history map does not stops recording the history.

![ezgif-5-37ac4e5992](https://user-images.githubusercontent.com/25341431/42520731-e45f4112-845e-11e8-85ba-8fb0f4bdb38b.gif)
![ezgif-5-120138a7bb](https://user-images.githubusercontent.com/25341431/42520917-6687cd1c-845f-11e8-9f79-effe39e39b7f.gif)

**Comment by RedayY** [comment]
Hey, this was something I developed. I remember the pause was only meant for stopping adding the recorded sessions into the DB and not stopping nodes from being displayed. This used to be a thing but it was removed.

**Comment by kaimdx** [comment]
There must be some miscommunication. Actually the 'pause' is meant to be the opposite: it stops showing nodes in historyMap, but the data is still recorded.

**Comment by RedayY** [comment]
I am not sure but to my standings this feature was complete

**Comment by kaimdx** [comment]
As shown in the screen cast above, currently the 'pause' button stops the saving to the backend database, but the nodes are still added to the historymap.

**Comment by RedayY** [comment]
I will try to look into it when I have a computer again.

**Comment by RedayY** [comment]
should be a small implementation

**Comment by kaimdx** [comment]
Thanks, Reday. I know you are busy, so take your time. 

There is another issue related to save and load #124. Again, it will be great if you can have a look, and just let me know if you won't have time for it currently.

**Comment by RedayY** [comment]
Just for transperance reasons I am mentioning this:

 - I don't have Internet at home right now it will be avaliable on the 27th July,
 - My Desk should be built up by then, I might be able to hotspot 4G connection to run SenseMap.

But I would be glad working on this and the other issue.
