### ISSUE TITLE
Detection url/page redirection

### ISSUE THREAD

**Issue by kaidatavis** [Vis4Sense/HistoryMap#68]
Currently SenseMap doesn't know if a URL change is caused by user (such as clicking a link) or by the website (redirection), so it always creates a new node, which may not make sense for the temporary url in page redirection.

**Comment by kaimdx** [comment]
Adding a screenshot of the google search result redirection with 'complete' status before the redirection. Might have to create a check specifically for google search.

<img width="1440" alt="screen shot 2017-10-20 at 10 18 43" src="https://user-images.githubusercontent.com/1853740/31814113-816ca930-b580-11e7-8a52-3e1276578967.png">
