### ISSUE TITLE
Save, Pause, and Load Sessions

### ISSUE THREAD

**Issue by kaidatavis** [Vis4Sense/HistoryMap#92]
For the discussions related to the development of the Save, Pause, and Load Sessions in SeneseMap.

**Comment by RedayY** [comment]
## Update:
 - Made Meeting Timeline for 17/10/17, you can find this also on the SideBar, but for those who want a direct link. [Meeting 17/10/17](https://github.com/Vis4Sense/SenseMapExtension/wiki/Meeting-17-10-17-Backend).
 - Cleaned UP, Code for Loading and Saving are now in Separate Documents.
 - Removed Node OFF, also removed code from browser provenance to the Saving Document.
 - Fixed Bugs with saving and pausing.
 - Even more buttons.... Sorry, One for retrieving User Session Information and one to load the actual selected Session.
 - Users can now Select their desired session that they want to load in the User Profile Box.
 - Closed Login ISSUE for now.
 - Made a new Branch for SaveLoad called rebuild-SaveLoad.
 - Pushed current state of SaveLoad to rebuild-Login.


 ## Points of Discussion for meeting:
 - Update in regards of Code
 - Question for "nodes" to backend
 - The Bug where nodes do not get added to the new session API bug yet still remains, Can we investiage this

**Comment by kaimdx** [comment]
Commit 630e88e92f4ca9482b6611849ada709b1abb0126 now uses UUID for node id (https://www.npmjs.com/package/uuid), so it is very unlikely that two nodes will have the same Id.

**Comment by kaimdx** [comment]
Save the ```historyMap.model``` to the database instead of ```nodes``` and ```tree```.
